jobs:
  Job1:
    name: Job 1
    steps: []
    repositories:
      - Pipelines_ValrravnAntJUnitSample:
          path: Ant-JUnit-Sample
          enabled: true
      - Root_HttpsTcqaTestBitbucketOrgTcqaTestSampleJavaAppMavenGitRefsHeadsMain:
          path: sample-java-app-maven.git
          enabled: true
